#!/bin/sh -e

GRAFANA_CONFIG="/etc/grafana/grafana.ini"

allow_unsigned () {
	if [ -e "${GRAFANA_CONFIG}" ]; then
		if ! grep -q 'revolve-energy-solarnetwork-datasource' "${GRAFANA_CONFIG}" 1>/dev/null 2>&1; then
			if grep -q '^allow_loading_unsigned_plugins' "${GRAFANA_CONFIG}" 1>/dev/null 2>&1; then
				sed -i \
					's/^allow_loading_unsigned_plugins.*/allow_loading_unsigned_plugins = "revolve-energy-solarnetwork-datasource"/' \
					"${GRAFANA_CONFIG}"
			elif grep -q 'allow_loading_unsigned_plugins' "${GRAFANA_CONFIG}" 1>/dev/null 2>&1; then
				sed -i \
					's/.*allow_loading_unsigned_plugins.*/allow_loading_unsigned_plugins = "revolve-energy-solarnetwork-datasource"/' \
					"${GRAFANA_CONFIG}"
			else
				echo 'allow_loading_unsigned_plugins = "revolve-energy-solarnetwork-datasource"' \
					>> "${GRAFANA_CONFIG}"
			fi
		fi
	fi
}

if [ "$1" = "configure" ]; then
	allow_unsigned
fi
